sudo: required
services:
  - docker

before_install: 
  - docker build -t adubeylabs/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true adubeylabs/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  environment: "Docker-react-env-1"
  bucket_name: "docker-react-tutorial"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY_ID"
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"



  